name: golangci-lint

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          golangci_lint_flags: "--config=.github/.golangci.yml"
